version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6
        environment:
          TZ: America/New_York
          PIPENV_VENV_IN_PROJECT: "TRUE"
          DATABASE_URL: postgres://postgres@localhost/usda_fns_ingestor
          CI_TESTING: "TRUE"

      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: usda_fns_ingestor

    steps:
      - checkout
      - restore_cache:
          key: v1-py-cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Setup environment
          command: |
            pip install pipenv
            pipenv install --dev

      - run:
          name: Install cf cli
          command: |
            mkdir -p $HOME/bin
            export PATH=$HOME/bin:$PATH
            curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary" | tar xzv -C $HOME/bin
            cf install-plugin autopilot -f -r CF-Community

      - save_cache:
          paths:
            - ./.venv
          key: v1-py-cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: USDA FNS Ingestor test suite
          command: cd usda_fns_ingestor && pipenv run coverage run ./manage.py test --settings=usda_fns_ingestor.settings.test

      - run:
          name: Build Coverage report
          command: cd usda_fns_ingestor && pipenv run coverage report

      - run:
          name: Flake8
          command: pipenv run flake8

      - run:
          name: Bandit
          command: pipenv run bandit -r . --ini .bandit

      - run:
          name: Codecov
          command: cd usda_fns_ingestor && pipenv run codecov

      - run:
          name: Deploy to dev (Temporary)
          command: |
            if [[ -n "${CIRCLE_BRANCH}" && "${CIRCLE_BRANCH}" != "master" ]]; then
              export PATH=$HOME/bin:$PATH
              cf login -a https://api.fr.cloud.gov -u $CF_USDA_FNS_DEV_USER -p $CF_USDA_FNS_DEV_PASS -o gsa-10x-prototyping -s dev
              cd usda_fns_ingestor
              cf zero-downtime-push usda-fns-ingestor -f manifests/manifest_dev_temp.yml
            else
              echo "Skipped"
            fi
      - run:
          name: Deploy to dev (Permanent)
          command: |
            if [[ -n "${CIRCLE_BRANCH}" && "${CIRCLE_BRANCH}" != "master" ]]; then
              export PATH=$HOME/bin:$PATH
              cf login -a https://api.fr.cloud.gov -u $NEW_CF_USDA_FNS_DEV_USER -p $NEW_CF_USDA_FNS_DEV_PASS -o usda-fns -s dev
              cd usda_fns_ingestor
              cf zero-downtime-push usda-fns-ingestor -f manifests/manifest_dev_perm.yml
            else
              echo "Skipped"
            fi
      - run:
          name: Deploy to staging (Temporary)
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_TAG}" ]]; then
              export PATH=$HOME/bin:$PATH
              cf login -a https://api.fr.cloud.gov -u $CF_USDA_FNS_STAGING_USER -p $CF_USDA_FNS_STAGING_PASS -o gsa-10x-prototyping -s usda_fns_staging
              cd usda_fns_ingestor
              cf zero-downtime-push usda-fns-ingestor -f manifests/manifest_staging_temp.yml
            else
              echo "Skipped"
            fi
      - run:
          name: Deploy to staging (Permanent)
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_TAG}" ]]; then
              export PATH=$HOME/bin:$PATH
              cf login -a https://api.fr.cloud.gov -u $NEW_CF_USDA_FNS_STAGING_USER -p $NEW_CF_USDA_FNS_STAGING_PASS -o usda-fns -s staging
              cd usda_fns_ingestor
              cf zero-downtime-push usda-fns-ingestor -f manifests/manifest_staging_perm.yml
            else
              echo "Skipped"
            fi
      - run:
          name: Deploy to prod (Temporary)
          command: |
            if [[ -n "${CIRCLE_TAG}" ]]; then
              export PATH=$HOME/bin:$PATH
              cf login -a https://api.fr.cloud.gov -u $CF_USDA_FNS_PROD_USER -p $CF_USDA_FNS_PROD_PASS -o gsa-10x-prototyping -s usda_fns_prod
              cd usda_fns_ingestor
              cf zero-downtime-push usda-fns-ingestor -f manifests/manifest_prod.yml
            else
              echo "Skipped"
            fi
      - run:
          name: Deploy to prod (Permanent)
          command: |
            if [[ -n "${CIRCLE_TAG}" ]]; then
              export PATH=$HOME/bin:$PATH
              cf login -a https://api.fr.cloud.gov -u $NEW_CF_USDA_FNS_PROD_USER -p $NEW_CF_USDA_FNS_PROD_PASS -o usda-fns -s prod
              cd usda_fns_ingestor
              cf zero-downtime-push usda-fns-ingestor -f manifests/manifest_prod.yml
            else
              echo "Skipped"
            fi

workflows:
  version: 2
  build-on--branches-and-tags:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/