---
applications:
- name: usda-fns-ingestor
  stack: cflinuxfs3
  buildpack: python_buildpack
  memory: 512mb
  routes:
    - route: usda-dvs-dev.app.cloud.gov
  instances: 1
  services:
   - usda-fns-ingestor-db
  env:
    DJANGO_SETTINGS_MODULE: usda_fns_ingestor.settings.cloud
